# Generated by Django 2.2.1 on 2019-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191026_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='pseudo',
            field=models.CharField(default='anonyme', max_length=20),
        ),
    ]
