# Generated by Django 2.2.1 on 2019-11-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_commentaires_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='mail',
            new_name='mails',
        ),
    ]
