# Generated by Django 2.2.1 on 2019-12-22 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='type',
            new_name='state',
        ),
        migrations.AddField(
            model_name='articles',
            name='image_article',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
