# Generated by Django 2.2.1 on 2019-12-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191222_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='sendable',
            field=models.BooleanField(default=True),
        ),
    ]
